language: "en-US"

reviews:
  profile: "chill"

  high_level_summary: true
  review_status: true
  request_changes_workflow: true
  poem: false

  auto_review:
    enabled: true
    drafts: false

  path_filters:
    - "!**/target/**"
    - "!**/build/**"
    - "!**/*.md"
    - "!**/node_modules/**"
    - "!**/*.log"
