# Application name
spring.application.name=Boka

# Active profile (remove this line to run in production)
spring.profiles.active=dev

# Server port
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/boka
spring.datasource.username=boka_user
spring.datasource.password=boka_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

# Security (Google OAuth2 Configuration)
# Replace with your actual credentials from Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=706537626571-0h7gnagvk7n4h8ppb646quodvdqi6eun.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Security (temporary - for local testing)
spring.security.user.name=admin
spring.security.user.password=admin
