CREATE TABLE bookings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    gym_class_id BIGINT                                  NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    booked_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE class_types
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    description      VARCHAR(500),
    default_capacity INTEGER                                 NOT NULL,
    duration_minutes INTEGER                                 NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_class_types PRIMARY KEY (id)
);

CREATE TABLE gym_classes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_type_id BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    gym_id        BIGINT                                  NOT NULL,
    start_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    capacity      INTEGER                                 NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_gym_classes PRIMARY KEY (id)
);

CREATE TABLE gym_info_cache
(
    id      BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    CONSTRAINT pk_gym_info_cache PRIMARY KEY (id)
);

CREATE TABLE gyms
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    latitude   DOUBLE PRECISION,
    longitude  DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_gyms PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255),
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    phone_number  VARCHAR(255),
    auth_provider VARCHAR(255)                            NOT NULL,
    provider_id   VARCHAR(255),
    role          VARCHAR(255)                            NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE class_types
    ADD CONSTRAINT uc_class_types_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE gym_classes
    ADD CONSTRAINT FK_GYM_CLASSES_ON_CLASS_TYPE FOREIGN KEY (class_type_id) REFERENCES class_types (id);

ALTER TABLE gym_classes
    ADD CONSTRAINT FK_GYM_CLASSES_ON_GYM FOREIGN KEY (gym_id) REFERENCES gym_info_cache (id);